apiVersion: apps/v1
kind: Deployment
metadata:
  name: assistant-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assistant-pod
  template:
    metadata:
      labels:
        app: assistant-pod
    spec:
      containers:
      - name: assistant-container
        image: uncodeit/assistant:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: OPENAI_API
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: API_KEY


---
apiVersion: v1
kind: Service
metadata:
  name: assistant-svc
spec:
  type: NodePort
  selector:
    app: assistant-pod
  ports:
  - port: 5000 # Service IP Port
    targetPort: 80 # Container Port
    nodePort: 30002 # Node Port/Host Port
    protocol: TCP